### ISSUE TITLE
Add a field at the end of the filename

### ISSUE THREAD

**Issue by sdenis6** [mer0m/datalogger-gui#3]
Hi mer0m,

In the case where several measures ares made with the same kind of instrument, it is not visually easy to distinguish in the filenames which file corresponds to which instrument. Would it be possible to add a field in the datalogger-gui to have the possibility to add a comment at the end of the filename ? 
For instance: 
20210310-093000-AG53123A_DeviceNI1.dat
20210310-093100-AG53123A_DeviceNI2.dat
20210310-093200-AG53123A_toto.dat
...

Thank you

**Comment by mer0m** [comment]
Hi,

Optional footer added.
When footer is enabled, the pattern is as following:

YYYYMDD-HHmmSS-deviceName_footer.dat

Available since this [commit](../tree/42b5f9c79bd1dacd1d9bf0622330938991b06fc5)

BR
